import { grade } from "./helpers.jsx";

let _data = null;
let _domain = "";

export function setPdfData(data, domain) {
  _data = data;
  _domain = domain;
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function addPageFooter(pdf, W, H) {
  const MB = 22;
  pdf.setFillColor(169, 0, 6);
  pdf.rect(0, H - MB, W, MB, "F");
  pdf.setFillColor(255, 100, 45);
  pdf.rect(0, H - 1.5, W, 1.5, "F");
  pdf.setFontSize(6.5);
  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "normal");
  const line1 = `BUIMB RESEARCH LLP  ·  Floor 1, Rajneel Complex, Lamachaur, Haldwani 263139`;
  pdf.text(line1, 10, H - MB + 7);
  const line2 = `contact@buimbdigital.com  ·  ${_domain}  ·  ${new Date().toLocaleDateString("en-GB")}`;
  pdf.text(line2, 10, H - MB + 13);
}

function addDividerPage(pdf, name, num, total, W, H) {
  pdf.setFillColor(26, 26, 46);
  pdf.rect(0, 0, W, H, "F");
  pdf.setFillColor(255, 100, 45);
  pdf.rect(0, 0, 5, H, "F");
  pdf.setFontSize(10);
  pdf.setTextColor(255, 100, 45);
  pdf.setFont("helvetica", "bold");
  pdf.text(`SECTION ${num} OF ${total}`, 18, 118);
  pdf.setFontSize(32);
  pdf.setTextColor(255, 255, 255);
  pdf.text(name, 18, 140);
  pdf.setDrawColor(255, 100, 45);
  pdf.setLineWidth(0.4);
  pdf.line(18, 148, W - 18, 148);
  pdf.setFontSize(9);
  pdf.setTextColor(155, 163, 175);
  pdf.setFont("helvetica", "normal");
  pdf.text(`SEO + AEO + GEO Audit Report  ·  ${_domain}  ·  ${new Date().toLocaleDateString("en-GB")}`, 18, 158);
}

function addCoverPage(pdf, W, H) {
  pdf.setFillColor(26, 26, 46);
  pdf.rect(0, 0, W, H, "F");
  pdf.setFillColor(255, 100, 45);
  pdf.rect(0, 0, W, 6, "F");
  pdf.setFontSize(28);
  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.text(_domain || "Website Audit", 18, 60);
  pdf.setFontSize(12);
  pdf.setTextColor(155, 163, 175);
  pdf.setFont("helvetica", "normal");
  pdf.text("Complete SEO + AEO + GEO Visibility Audit Report", 18, 74);
  pdf.setFillColor(36, 36, 66);
  pdf.roundedRect(18, 88, W - 36, 38, 4, 4, "F");
  pdf.setFontSize(10);
  pdf.setTextColor(155, 163, 175);
  pdf.text("OVERALL SCORE", 30, 100);
  pdf.setFontSize(26);
  pdf.setTextColor(255, 100, 45);
  pdf.setFont("helvetica", "bold");
  pdf.text(`${_data?.overall || 0} / 100  (Grade ${grade(_data?.overall || 0)})`, 30, 116);
  const modules = [
    { label: "SEO", score: _data?.mods?.seo?.score || 0, col: [255, 100, 45] },
    { label: "AEO", score: _data?.mods?.aeo?.score || 0, col: [16, 185, 129] },
    { label: "GEO", score: _data?.mods?.geo?.score || 0, col: [139, 92, 246] },
  ];
  modules.forEach((m, idx) => {
    const x = 18 + idx * 62;
    pdf.setFillColor(36, 36, 66);
    pdf.roundedRect(x, 134, 58, 28, 3, 3, "F");
    pdf.setFontSize(9);
    pdf.setTextColor(155, 163, 175);
    pdf.setFont("helvetica", "normal");
    pdf.text(m.label, x + 4, 144);
    pdf.setFontSize(14);
    pdf.setTextColor(m.col[0], m.col[1], m.col[2]);
    pdf.setFont("helvetica", "bold");
    pdf.text(`${m.score}/100`, x + 4, 156);
  });
  const calItems = (_data?.calendar || []).reduce((a, m) => a + (m.items || []).length, 0);
  const kwTotal = Object.values(_data?.keywords || {}).flat().length;
  const parts = [
    { num: "PART 1", title: "SEO / AEO / GEO Audit Report", detail: "89 checks across 14 categories" },
    { num: "PART 2", title: "6-Month Content Calendar", detail: `${calItems} content pieces` },
    { num: "PART 3", title: "SEO Strategy, Competitors & Keywords", detail: `12-month plan · ${(_data?.competitors || []).length} competitors · ${kwTotal} keywords` },
  ];
  let py = 180;
  parts.forEach((p) => {
    pdf.setFillColor(42, 42, 72);
    pdf.roundedRect(18, py, W - 36, 24, 3, 3, "F");
    pdf.setFillColor(255, 100, 45);
    pdf.roundedRect(18, py, 28, 24, 3, 3, "F");
    pdf.setFontSize(7);
    pdf.setTextColor(255, 255, 255);
    pdf.setFont("helvetica", "bold");
    pdf.text(p.num, 19, py + 10);
    pdf.setFontSize(11);
    pdf.setTextColor(255, 255, 255);
    pdf.text(p.title, 52, py + 11);
    pdf.setFontSize(8);
    pdf.setTextColor(155, 163, 175);
    pdf.setFont("helvetica", "normal");
    pdf.text(p.detail, 52, py + 19);
    py += 30;
  });
  pdf.setFillColor(255, 100, 45);
  pdf.rect(0, H - 8, W, 8, "F");
  pdf.setFontSize(8);
  pdf.setTextColor(255, 255, 255);
  pdf.text(`Generated by AI Analysis  ·  ${new Date().toLocaleDateString("en-GB")}  ·  CONFIDENTIAL`, 18, H - 2);
}

async function capturePanel(panelEl) {
  const html2canvas = (await import("html2canvas")).default;
  const saved = {
    className: panelEl.className,
    display: panelEl.style.display,
    visibility: panelEl.style.visibility,
    position: panelEl.style.position,
    width: panelEl.style.width,
  };
  panelEl.style.display = "block";
  panelEl.style.visibility = "visible";
  panelEl.style.position = "relative";
  panelEl.style.width = "1180px";
  // expand all collapsible sections
  panelEl.querySelectorAll("[data-cat-open]").forEach((el) => {
    el.setAttribute("data-cat-open", "true");
  });
  await sleep(350);
  const canvas = await html2canvas(panelEl, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff",
    windowWidth: 1220,
    width: 1180,
    scrollX: 0,
    scrollY: 0,
    imageTimeout: 20000,
  });
  Object.assign(panelEl.style, saved);
  return canvas;
}

function addCanvasToPDF(pdf, canvas, A4_W, A4_H) {
  const cW = canvas.width, cH = canvas.height;
  const ML = 10, MR = 10, MT = 10;
  const cntW = A4_W - ML - MR;
  const cntH = A4_H - MT - 24;
  const safeH = cntH * 0.93;
  const pxMM = cW / cntW;
  const pxPg = safeH * pxMM;
  const pages = Math.ceil(cH / pxPg);
  for (let pg = 0; pg < pages; pg++) {
    pdf.addPage();
    pdf.setFillColor(255, 255, 255);
    pdf.rect(0, 0, A4_W, A4_H, "F");
    pdf.setFillColor(255, 100, 45);
    pdf.rect(0, 0, 2, A4_H, "F");
    const srcY = pg * pxPg;
    const srcH = Math.min(pxPg, cH - srcY);
    const dstH = srcH / pxMM;
    const sl = document.createElement("canvas");
    sl.width = cW;
    sl.height = Math.ceil(srcH);
    const ctx = sl.getContext("2d");
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, cW, Math.ceil(srcH));
    ctx.drawImage(canvas, 0, srcY, cW, srcH, 0, 0, cW, srcH);
    pdf.addImage(sl.toDataURL("image/jpeg", 0.92), "JPEG", ML, MT, cntW, dstH, "", "FAST");
    addPageFooter(pdf, A4_W, A4_H);
  }
}

export async function exportPDF(tabPanelRefs, onProgress) {
  const { jsPDF } = await import("jspdf");
  const A4_W = 210, A4_H = 297;
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const TAB_NAMES = ["Overview", "SEO Analysis", "AEO Analysis", "GEO Analysis", "Action Plan", "SEO Strategy", "Competitors", "Keywords"];

  onProgress?.("Creating cover page...", 3);
  addCoverPage(pdf, A4_W, A4_H);

  const panels = Object.entries(tabPanelRefs).filter(([, el]) => el != null);

  for (let i = 0; i < panels.length; i++) {
    const [, panelEl] = panels[i];
    const name = TAB_NAMES[i] || `Section ${i + 1}`;
    const pct = Math.round(5 + (i / panels.length) * 90);
    onProgress?.(`Capturing ${name}...`, pct);
    pdf.addPage();
    addDividerPage(pdf, name, i + 1, panels.length, A4_W, A4_H);
    try {
      const canvas = await capturePanel(panelEl);
      addCanvasToPDF(pdf, canvas, A4_W, A4_H);
    } catch (e) {
      console.warn(`Capture failed for ${name}:`, e);
      pdf.addPage();
      pdf.setFontSize(14);
      pdf.setTextColor(239, 68, 68);
      pdf.text(`Could not capture ${name}`, 20, 100);
    }
  }

  onProgress?.("Saving PDF...", 98);
  await sleep(400);
  const safeDomain = (_domain || "audit").replace(/[^a-z0-9.-]/gi, "-");
  pdf.save(`${safeDomain}-seo-aeo-geo-report-${new Date().toISOString().split("T")[0]}.pdf`);
  onProgress?.("Done!", 100);
}
